name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Export Environment Variables
      run: echo '${{ secrets.ENV }}' > .env

    - name: Create wrangler.toml from template
      run: |
        cp wrangler.example.toml wrangler.toml
        sed -i 's/<PROJECT_NAME>/${{ secrets.CLOUDFLARE_PROJECT_NAME }}/g' wrangler.toml
        sed -i 's/<DATABASE_NAME>/${{ secrets.CLOUDFLARE_DATABASE_NAME }}/g' wrangler.toml
        sed -i 's/<DATABASE_ID>/${{ secrets.CLOUDFLARE_DATABASE_ID }}/g' wrangler.toml

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Run database migrations
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: d1 migrations apply DB --remote

    - name: Deploy to CloudFlare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}